
package br.org.catolicasc.produtos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoService", targetNamespace = "http://www.catolicasc.org.br/produtos/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.catolicasc.produtos.Produtos
     */
    @WebMethod
    @WebResult(name = "produtos", targetNamespace = "http://www.catolicasc.org.br/produtos/", partName = "parameters")
    @Action(input = "http://www.catolicasc.org.br/produtos/ProdutoService/listarProdutosRequest", output = "http://www.catolicasc.org.br/produtos/ProdutoService/listarProdutosResponse")
    public Produtos listarProdutos(
        @WebParam(name = "listarProduto", targetNamespace = "http://www.catolicasc.org.br/produtos/", partName = "parameters")
        ProdutoRequest parameters);

}
