
package br.com.cervejaria.app.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListagemCerveja", targetNamespace = "http://service.app.cervejaria.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemCerveja {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.cervejaria.app.service.Cerveja>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLivro", targetNamespace = "http://service.app.cervejaria.com.br/", className = "br.com.cervejaria.app.service.ListarLivro")
    @ResponseWrapper(localName = "listarLivroResponse", targetNamespace = "http://service.app.cervejaria.com.br/", className = "br.com.cervejaria.app.service.ListarLivroResponse")
    @Action(input = "http://service.app.cervejaria.com.br/ListagemCerveja/listarLivroRequest", output = "http://service.app.cervejaria.com.br/ListagemCerveja/listarLivroResponse")
    public List<Cerveja> listarLivro();

}
