
package br.com.cervejaria.app.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListagemCervejaService", targetNamespace = "http://service.app.cervejaria.com.br/", wsdlLocation = "http://localhost:8181/cervejas?wsdl")
public class ListagemCervejaService
    extends Service
{

    private final static URL LISTAGEMCERVEJASERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAGEMCERVEJASERVICE_EXCEPTION;
    private final static QName LISTAGEMCERVEJASERVICE_QNAME = new QName("http://service.app.cervejaria.com.br/", "ListagemCervejaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8181/cervejas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAGEMCERVEJASERVICE_WSDL_LOCATION = url;
        LISTAGEMCERVEJASERVICE_EXCEPTION = e;
    }

    public ListagemCervejaService() {
        super(__getWsdlLocation(), LISTAGEMCERVEJASERVICE_QNAME);
    }

    public ListagemCervejaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAGEMCERVEJASERVICE_QNAME, features);
    }

    public ListagemCervejaService(URL wsdlLocation) {
        super(wsdlLocation, LISTAGEMCERVEJASERVICE_QNAME);
    }

    public ListagemCervejaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAGEMCERVEJASERVICE_QNAME, features);
    }

    public ListagemCervejaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemCervejaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListagemCerveja
     */
    @WebEndpoint(name = "ListagemCervejaPort")
    public ListagemCerveja getListagemCervejaPort() {
        return super.getPort(new QName("http://service.app.cervejaria.com.br/", "ListagemCervejaPort"), ListagemCerveja.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemCerveja
     */
    @WebEndpoint(name = "ListagemCervejaPort")
    public ListagemCerveja getListagemCervejaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.app.cervejaria.com.br/", "ListagemCervejaPort"), ListagemCerveja.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAGEMCERVEJASERVICE_EXCEPTION!= null) {
            throw LISTAGEMCERVEJASERVICE_EXCEPTION;
        }
        return LISTAGEMCERVEJASERVICE_WSDL_LOCATION;
    }

}
